### ISSUE TITLE
Electrical Troubleshooting on BunnyBot

### ISSUE THREAD

**Issue by Lakemonsters2635** [Lakemonsters2635/BunnyBots2024#14]
Found multiple electrical issues on BunnyBot2024 will discuss troubleshooting steps and symptoms will be found here.

**Comment by Lakemonsters2635** [comment]
@SuleymanSade Suleyman is working on updating the MonsterDocs for the troubleshooting problems we found working on the Bunny bot.

**Comment by Lakemonsters2635** [comment]
It is almost done @SuleymanSade is adding images

**Comment by jwaltner** [comment]
Troubleshooting documentation created and merged into MonsterDocs.
