### ISSUE TITLE
Base Code Vision Integration

### ISSUE THREAD

**Issue by jwaltner** [Lakemonsters2635/BunnyBots2024#3]
The base robot code needs an example of performing both navigation (moving robot as well as rotating the robot) and subsystem operation (i.e. moving arm subsystem and then shooting) in response to vision detections.  The subsystem example may not belong in the base robot code as subsystems may vary, but the navigation examples do belong there.  

After the code is figured out on Eclipse, it needs to be added to base bunny bot swerve drive code.

**Comment by Lakemonsters2635** [comment]
Complete for Eclipse, need to confirm on the bunnybot.

**Comment by jwaltner** [comment]
Base vision code completed Dec 5 on BunnyBot
