### ISSUE TITLE
Eclipse Autos - Research for BunnyBots

### ISSUE THREAD

**Issue by jwaltner** [Lakemonsters2635/BunnyBots2024#7]
For Suleyman:

eclipse autos.  Do not continuously grab the target like we did on Saturday Oct 19th. Kick off a command which sees how much it needs to turn and then keeps turning the bot until it gets close to that target.  Only check where your target is in initialize.  Do not check where target is in execute like we were doing on Saturday.

After that works, tie it together so you can drive the robot into a position and then hit a button to turn to April tag then shoot with the proper arm angle based off of April tag.

**Comment by jwaltner** [comment]
harmonize bunny bot autos and drivetrain with eclipse... we do not want to have two significantly different definitions of swerve / autos.

**Comment by Lakemonsters2635** [comment]
Harmonization complete. Yay!
