### ISSUE TITLE
Current measurements for detecting vacuum.

### ISSUE THREAD

**Issue by jwaltner** [Lakemonsters2635/BunnyBots2024#8]
Need current measurements to detect when the vacuum has grabbed a balloon.  This should be able to be obtained from the power distribution hub.

Michael found this code... could potentially work as a starting point.

```java
import edu.wpi.first.wpilibj.PowerDistributionPanel;
public class Robot extends TimedRobot {
    private PowerDistributionPanel pdp = new PowerDistributionPanel();
    @Override
    public void robotPeriodic() {
        // Read the current draw on channel 0
        double current = pdp.getCurrent(0);
        System.out.println("Current on channel 0: " + current + "A");
    }
}
```

- [X] The simple code for getting the current value is working on Eclipse
- [ ] Need to test specific values to see if it has a balloon
- [ ] Need to change PDH and id for BunnyBots2024

**Comment by jwaltner** [comment]
@An-JieYu , please take a look at current measurements, we will need to do this so we can figure out when we grabbed the balloon.  Thx.

**Comment by SuleymanSade** [comment]
* The simple code for getting the current value is working on Eclipse
* Need to test specific values to see if it has a balloon
* Need to change PDH and id for BunnyBots2024

**Comment by jwaltner** [comment]
Updateed the issue to have a checklist for the items called out by @suleymansade

**Comment by Lakemonsters2635** [comment]
https://github.com/Lakemonsters2635/BunnyBots2024/blob/feature/currentMeasurement/src/main/java/frc/robot/subsystems/VacuumSubsystem.java

**Comment by Lakemonsters2635** [comment]
We tested it and the currents overlap for when it has and doesn't have a balloon so we aren't going to use it since it is hard to determine using the current. Also, it will fluctuate with the battery level.

**Comment by jwaltner** [comment]
Agreed that we can not use this as originally intended.  However, it is good to keep this code around and document in MonsterDocs what we did and point to the example code which shows how to read current in case we need it for something else in the future.  Note that this current draw could also be used to help monitor motors to see if they are stalled.  When a motor stalls, its current will go up.  This is due to physics and could make a good physics lab... but danger of that is that you might burn out motors... I will close this issue and create a new issue for MonsterDocs to document these ideas.
